server:
  port: 8000

spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:memdb #jdbc:h2:file:./data/testdb
    username: sa
    password: p
    driverClassName: org.h2.Driver
  sql:
    init:
      schema: classpath:schema.sql
      mode: always

app:
  springdata:
    enabled: true